### ISSUE TITLE
002C | Fehlerbehandlung

### ISSUE THREAD

**Issue by mbedded** [Technik-Tueftler/TeTueChallenge#14]
Hallo,
ich möchte an der nächsten Challenge gerne Teilnehmen. Allerdings ist mir die Fehlerbehandlung unklar, da nicht beschrieben.
Soll ich im Modul davon ausgehen, dass die Aufrufe immer korrekt sind? Soll ich eine Exception auslösen oder reicht die Rückgabe von einer Fehlermeldung als String statt der Zahlen?

**Mögliche Fehler:**
- Datei ist nicht vorhanden (falsche Eingabe)
- Bei der Funktion `count_words_from_line`:
  - Der Parameter *Zeile* ist negativ
  - Der Parameter *Zeile* ist größer als die Anzahl der Zeilen im Dokument

VG

**Comment by Technik-Tueftler** [comment]
Da es rein um die Aufgabe geht und den Lösungsweg, vernachlässigen wir die Fehlerbehandlung. Es wird immer davon ausgegangen, dass die übergebenen Parameter im korrekten Wertebereich sind und der übergebene Pfad existiert.

**Comment by mbedded** [comment]
Danke für die Info. Dann werfe ich die rudimentäre Fehlerbehandlung raus :)
