### ISSUE TITLE
TeTueChallenge C002C - Request for second test file

### ISSUE THREAD

**Issue by Korbi-code** [Technik-Tueftler/TeTueChallenge#15]
# Aktuell
In den Anforderungen ist definiert, dass nur zwei Dateien erlaubt sind. 
## Files: 
1. source/twitchname.py (mandatory)
2. test/twitchname_test.py (optional)

# Anfrage
In den "Aufgaben" und "Zusatzaufgaben Aufgaben" Funktionsprototypen ist ein Pfad zu einem Textdokument als Parameter definiert. Zum Testen der eigenen Implementierung sollte somit ein eigenes Test Textfile erstellt werden können. Wäre schade dieses später nicht pushen zu können. 

## Files: 
1. source/twitchname.py (mandatory)
2. test/twitchname_test.py (optional)
3. test/twitchname_test.txt (optional)

**Comment by KerstenSchaller** [comment]
Ich stimme dem nicht zu... 
Wir brauchen ein Testfile inkl ground truth vom Tetü.

Sonst gibt es wieder etliche Unklarheiten wie: 
- Ist ein "Hans-Peter" ein oder zwei Wörter
- Ist eine Zahl ein Wort? 
- Wie behandelt man Überschriften? (Ich hab mit dem Readme.md als testfile angefangen und mich direkt gefragt wie man ## behandelt)

Wenn wir das testfile selber machen weiß ja keiner ob wir nicht nach komplett unterschiedlichen Regeln zählen.

**Comment by Korbi-code** [comment]
Dann brauchen wir aber eigentlich auch keine eigenen Testfiles. 

Dann würde es ja reichen, dass der Tetü uns ein Testfile.py liefert mit x vordefinierten Testcases, die jede Implementierung gegen sein .txt File testet.

**Comment by Technik-Tueftler** [comment]
Ich würde gerne davon wegkommen, dass es nur eine gültige Lösung gibt, welche ich vorgebe. Prinzipiell ist es egal, ob z.B. Hans-Peter ein oder zwei Wörter sind oder ob eine Zahl ein Wort ist. Wenn ich das bestimme müsste ich festlegen, wie ein Zitat oder Wort erkannt wird. Beispiel:
*Ein Zitat beginnt mit <">, hat mindestens ein weiteres <"> und endet in einer neuen Zeile mit <-- + Name>*
--> Wenn ich das so schreibe, nehme ich jede Kreativität raus für uns. Vielleicht gibt es eine schönere Lösung dafür. 

Oder am Beispiel für die Zahl. Wenn eine Zahl für euch ein Wort ist, ist das für mich ok. Wenn ein Wort für euch mindestens 7 Zeichen haben muss und mit einem <. ! ?> beendet wird, ist das auch ok. Schreibt einfach in eurer Funktion ein Kommentar, wo ihr kurz beschreibt, was ein Wort ist.

Wenn ich anfange hierfür Regeln und Testfiles zu erstellen, sind 3 Wochen zu wenig, da wir erstmal 99,3667 Wochen diskutieren was "richtig" oder "falsch" ist.

Danke aber für euren Input, sage ich am Mittwoch nochmal im Stream =) Noch ne Info hier:
https://www.ionos.de/digitalguide/server/knowhow/ascii-american-standard-code-for-information-interchange/
Für mich ergibt es Sinn, wenn ein Wort nur aus Großbuchstaben und Kleinbuchstaben bestehen kann.
