### ISSUE TITLE
Die Requirements sind schon wieder unklar :)

### ISSUE THREAD

**Issue by KerstenSchaller** [Technik-Tueftler/TeTueChallenge#16]
Ich frage mich zB was ist ein Wort?  
Wenn ich die Readme.md als Beispiel nehme habe ich direkt ne Menge Sonderfälle die ich als Wörter zählen könnte oder nicht.
Dazu gehören:
- ##
- 1. , 2. usw
- Außerdem bin ich mir nicht sicher ob Hans-Peter als ein oder 2 Wörter gilt
- Was ist ein Zitat? Alles was in " steht?

**Comment by Technik-Tueftler** [comment]
Ich würde gerne davon wegkommen, dass es nur eine gültige Lösung gibt, welche ich vorgebe. Prinzipiell ist es egal, ob z.B. Hans-Peter ein oder zwei Wörter sind oder ob eine Zahl ein Wort ist. Wenn ich das bestimme müsste ich festlegen, wie ein Zitat oder Wort erkannt wird. Beispiel:
*Ein Zitat beginnt mit <">, hat mindestens ein weiteres <"> und endet in einer neuen Zeile mit <-- + Name>*
--> Wenn ich das so schreibe, nehme ich jede Kreativität raus für uns. Vielleicht gibt es eine schönere Lösung dafür. 

Oder am Beispiel für die Zahl. Wenn eine Zahl für euch ein Wort ist, ist das für mich ok. Wenn ein Wort für euch mindestens 7 Zeichen haben muss und mit einem <. ! ?> beendet wird, ist das auch ok. Schreibt einfach in eurer Funktion ein Kommentar, wo ihr kurz beschreibt, was ein Wort ist.

Wenn ich anfange hierfür Regeln und Testfiles zu erstellen, sind 3 Wochen zu wenig, da wir erstmal 99,3667 Wochen diskutieren was "richtig" oder "falsch" ist.

Danke aber für euren Input, sage ich am Mittwoch nochmal im Stream =) Noch ne Info hier:
https://www.ionos.de/digitalguide/server/knowhow/ascii-american-standard-code-for-information-interchange/
Für mich ergibt es Sinn, wenn ein Wort nur aus Großbuchstaben und Kleinbuchstaben bestehen kann.
